name: Create Jira issue
on:
  issues:
    types:
      - opened
jobs:
  create-issue:
    name: Create Jira issue
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Issue Parser
        uses: stefanbuck/github-issue-praser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/01-feat-template.yml

      - name: Log Issue Parser
        run: |
          echo '${{ steps.issue-parser.outputs.jsonString }}'

      - name: Log created issue
        run: |
         echo "Jira Issue ${{ steps.issue-parser.outputs.parentKey }}/${{ steps.create.outputs.issue }} was created"
         echo "${{ github.event.issue.body }}"

      - name: Checkout main code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Create branch with Ticket number
        run: |
          ISSUE_NUMBER="${{ steps.issue-parser.outputs.issueparser_parentKey }}"
          BRANCH_NAME="feat/${ISSUE_NUMBER}"
          git checkout -b "${BRANCH_NAME}"
          git push origin "${BRANCH_NAME}"

      - name: Update issue title
        uses: actions-cool/issues-helper@v3
        with:
          actions: "update-issue"
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "[${{ steps.create.outputs.issue }}] ${{ github.event.issue.title }}"
